# Generated by Django 2.1.7 on 2019-03-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='msmtType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='msmtType', to='hnet.MeasurementType'),
            preserve_default=False,
        ),
    ]
