# Generated by Django 2.1.7 on 2019-03-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0002_measurement_msmttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
