# Generated by Django 2.1.7 on 2019-03-07 16:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hnet', '0004_auto_20190306_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly'), (90, 'Quarterly')], default=1)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 3, 7, 16, 8, 19, 813737))),
                ('comments', models.TextField(blank=True, null=True)),
                ('msmtType', models.ManyToManyField(to='hnet.MeasurementType')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_grpmsmt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
