# Generated by Django 2.1.7 on 2019-03-07 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0006_auto_20190307_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmeasurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
