# Generated by Django 2.1.7 on 2019-03-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0007_auto_20190307_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmeasurementrecording',
            name='msmtType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupMeasurementRecording', to='hnet.MeasurementType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmeasurement',
            name='groupMeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMeasurementTemplate', to='hnet.GroupMeasurementTemplate'),
        ),
    ]
