# Generated by Django 2.0.9 on 2019-03-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0008_auto_20190307_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtype',
            name='max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupmeasurementtemplate',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly'), (90, 'Quarterly'), (182, 'Semi annually'), (365, 'Annually')], default=1),
        ),
    ]
