# Generated by Django 2.0.9 on 2019-03-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0009_auto_20190330_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='msmtType',
            new_name='measurementType',
        ),
    ]
