# Generated by Django 2.0.9 on 2019-03-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0010_auto_20190330_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='healthnet.Patient'),
        ),
    ]
