# Generated by Django 2.1.7 on 2019-03-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinfo',
            name='ts',
        ),
    ]
