# Generated by Django 2.1.7 on 2019-03-06 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0002_remove_medicalinfo_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 6)),
        ),
    ]
