# Generated by Django 2.1.7 on 2019-03-07 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0003_auto_20190306_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 7)),
        ),
    ]
