# Generated by Django 2.0.9 on 2019-03-27 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0004_auto_20190307_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('insurance', models.CharField(max_length=50)),
                ('emergencyContactName', models.CharField(blank=True, max_length=50)),
                ('emergencyContactNumber', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(default=datetime.date(1000, 1, 1))),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('allergies', models.CharField(blank=True, max_length=250)),
                ('prefHospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital')),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 27)),
        ),
    ]
