# Generated by Django 2.0.9 on 2019-03-29 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0007_auto_20190328_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 29)),
        ),
        migrations.AlterField(
            model_name='scriptitem',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scriptItems', to='healthnet.Script'),
        ),
    ]
