# Generated by Django 2.0.9 on 2019-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0008_auto_20190329_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptitem',
            name='refills',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
